/* Permissions file generated by flow2code */

/*=== f2c_start __file ===*/

/*=== f2c_end __file ===*/

const permissions = {
	"product.add": "User can add / modify / delete a product",
};

export default permissions;
